import os
SCRIPT_DIR = os.path.dirname(__file__)

available1 = [
    "Decompositions/CCNOTAdjointControlled.qs",
    # "Decompositions/CCNOT.qs",
    # "Decompositions/CCNOTAdjoint.qs",
    # "Decompositions/CCNOTControlled.qs",
    # "Decompositions/CNOT.qs",
    # "Decompositions/CNOTAdjoint.qs",
    # "Decompositions/CNOTControlled.qs",
    # "Decompositions/CX.qs",
    # "Decompositions/CXAdjoint.qs",
    # "Decompositions/CXControlled.qs",
    # "Decompositions/CY.qs",
    # "Decompositions/CYAdjoint.qs",
    # "Decompositions/CYControlled.qs",
    # "Decompositions/CZ.qs",
    # "Decompositions/CZAdjoint.qs",
    # "Decompositions/CZControlled.qs",
    # # TODO:   "Decompositions/ExpFrac.qs",
    # # TODO: "Decompositions/ExpFracAdjoint.qs",
    # # TODO: "Decompositions/ExpFracControlled.qs",
    # "Decompositions/H.qs",
    # "Decompositions/HAdjoint.qs",
    # "Decompositions/HControlled.qs",
    # "Decompositions/I.qs",
    # "Decompositions/IAdjoint.qs",
    # "Decompositions/IControlled.qs",
    # "Decompositions/M.qs",
    # "Decompositions/MResetX.qs",
    # "Decompositions/MResetY.qs",
    # "Decompositions/MResetZ.qs",
    # "Decompositions/R.qs",
    # "Decompositions/RAdjoint.qs",
    # "Decompositions/RControlled.qs",
    # "Decompositions/R1.qs",
    # "Decompositions/R1Adjoint.qs",
    # "Decompositions/R1Controlled.qs",
    # "Decompositions/R1Frac.qs",
    # "Decompositions/R1FracAdjoint.qs",
    # "Decompositions/R1FracControlled.qs",
    # "Decompositions/RFrac.qs",
    # "Decompositions/RFracAdjoint.qs",
    # "Decompositions/RFracControlled.qs",
    # "Decompositions/Reset.qs",
    # "Decompositions/ResetAdjoint.qs",
    # "Decompositions/ResetControlled.qs",
    # "Decompositions/Rx.qs",
    # "Decompositions/RxAdjoint.qs",
    # "Decompositions/RxControlled.qs",
    # "Decompositions/Ry.qs",
    # "Decompositions/RyAdjoint.qs",
    # "Decompositions/RyControlled.qs",
    # "Decompositions/Rz.qs",
    # "Decompositions/RzAdjoint.qs",
    # "Decompositions/RzControlled.qs",
    # "Decompositions/S.qs",
    # "Decompositions/SAdjoint.qs",
    # "Decompositions/SControlled.qs",
    # "Decompositions/SWAP.qs",
    # "Decompositions/SWAPAdjoint.qs",
    # "Decompositions/SWAPControlled.qs",
    # "Decompositions/SetToBasisState.qs",
    # "Decompositions/T.qs",
    # "Decompositions/TAdjoint.qs",
    # "Decompositions/TControlled.qs",
    # "Decompositions/X.qs",
    # "Decompositions/XAdjoint.qs",
    # "Decompositions/XControlled.qs",
    # "Decompositions/Y.qs",
    # "Decompositions/YAdjoint.qs",
    # "Decompositions/YControlled.qs",
    # "Decompositions/Z.qs",
    # "Decompositions/ZAdjoint.qs",
    # "Decompositions/ZControlled.qs",
]

available3 = ["Intrinsic/ApplyControlledX.qs",
              "Intrinsic/ApplyControlledZ.qs",
              "Intrinsic/ApplyUncontrolledH.qs",
              "Intrinsic/ApplyUncontrolledRx.qs", "Intrinsic/ApplyUncontrolledRy.qs", "Intrinsic/ApplyUncontrolledRz.qs", "Intrinsic/ApplyUncontrolledS.qs", "Intrinsic/ApplyUncontrolledSAdj.qs", "Intrinsic/ApplyUncontrolledSWAP.qs", "Intrinsic/ApplyUncontrolledT.qs", "Intrinsic/ApplyUncontrolledTAdj.qs", "Intrinsic/ApplyUncontrolledX.qs", "Intrinsic/ApplyUncontrolledY.qs", "Intrinsic/ApplyUncontrolledZ.qs", "Intrinsic/MZ.qs", "Intrinsic/Reset.qs", "Decompositions/AssertOperationsEqualInPlace.qs", "Decompositions/AssertOperationsEqualReferenced.qs", "Decompositions/CCNOTFromCCZ.qs", "Decompositions/CNOTFromSinglyControlled.qs", "Decompositions/CX.qs", "Decompositions/CYFromCNOT.qs", "Decompositions/CZFromSinglyControlled.qs", "Decompositions/ExpFracFromExpUtil.qs", "Decompositions/ExpFromExpUtil.qs", "Decompositions/ExpUtil.qs",
              "Decompositions/HFromSinglyControlled.qs", "Decompositions/I.qs", "Decompositions/Measure.qs", "Decompositions/MResetXExplicit.qs", "Decompositions/MResetYExplicit.qs", "Decompositions/MResetZExplicit.qs", "Decompositions/MWithPostPrep.qs", "Decompositions/PreparePostMNoop.qs", "Decompositions/RFromSinglyControlledR1.qs", "Decompositions/R1FromSinglyControlled.qs", "Decompositions/R1Frac.qs", "Decompositions/ResetAll.qs", "Decompositions/RFrac.qs", "Decompositions/RxFromSinglyControlled.qs", "Decompositions/RyFromSinglyControlled.qs", "Decompositions/RzFromSinglyControlled.qs", "Decompositions/SFromSinglyControlled.qs", "Decompositions/SWAPFromSinglyControlled.qs", "Decompositions/TFromSinglyControlled.qs", "Decompositions/XFromSinglyControlled.qs", "Decompositions/YFromSinglyControlled.qs", "Decompositions/ZFromSinglyControlled.qs", "Decompositions/SetToBasisState.qs", "Decompositions/Utils.qs"]

available4 = ["Intrinsic/ApplyControlledX.qs", "Intrinsic/ApplyControlledZ.qs", "Intrinsic/ApplyUncontrolledH.qs", "Intrinsic/ApplyUncontrolledRx.qs", "Intrinsic/ApplyUncontrolledRy.qs", "Intrinsic/ApplyUncontrolledRz.qs", "Intrinsic/ApplyUncontrolledS.qs", "Intrinsic/ApplyUncontrolledSAdj.qs", "Intrinsic/ApplyUncontrolledSWAP.qs", "Intrinsic/ApplyUncontrolledT.qs", "Intrinsic/ApplyUncontrolledTAdj.qs", "Intrinsic/ApplyUncontrolledX.qs", "Intrinsic/ApplyUncontrolledY.qs", "Intrinsic/ApplyUncontrolledZ.qs", "Intrinsic/MZ.qs", "Intrinsic/Reset.qs", "Decompositions/AssertOperationsEqualInPlace.qs", "Decompositions/AssertOperationsEqualReferenced.qs", "Decompositions/CCNOTFromCCZ.qs", "Decompositions/CNOTFromSinglyControlled.qs", "Decompositions/CX.qs", "Decompositions/CYFromCNOT.qs", "Decompositions/CZFromSinglyControlled.qs", "Decompositions/ExpFracFromExpUtil.qs", "Decompositions/ExpFromExpUtil.qs",
              "Decompositions/ExpUtil.qs", "Decompositions/HFromSinglyControlled.qs", "Decompositions/I.qs", "Decompositions/M.qs", "Decompositions/MeasureWithNoReuse.qs", "Decompositions/MResetXExplicit.qs", "Decompositions/MResetYExplicit.qs", "Decompositions/MResetZExplicit.qs", "Decompositions/PreparePostMNoop.qs", "Decompositions/RFromSinglyControlledR1.qs", "Decompositions/R1FromSinglyControlled.qs", "Decompositions/R1Frac.qs", "Decompositions/ResetAll.qs", "Decompositions/RFrac.qs", "Decompositions/RxFromSinglyControlled.qs", "Decompositions/RyFromSinglyControlled.qs", "Decompositions/RzFromSinglyControlled.qs", "Decompositions/SFromSinglyControlled.qs", "Decompositions/SWAPFromSinglyControlled.qs", "Decompositions/TFromSinglyControlled.qs", "Decompositions/XFromSinglyControlled.qs", "Decompositions/YFromSinglyControlled.qs", "Decompositions/ZFromSinglyControlled.qs", "Decompositions/SetToBasisState.qs", "Decompositions/Utils.qs"]
