import os
SCRIPT_DIR = os.path.dirname(__file__)

available1 = [
    "Decompositions/CCNOT.qs",
    "Decompositions/CCNOTAdjoint.qs",
    "Decompositions/CCNOTControlled.qs",
    "Decompositions/CCNOTAdjointControlled.qs",
    "Decompositions/CCNOTControlledAdjoint.qs",
    "Decompositions/CNOT.qs",
    "Decompositions/CNOTAdjoint.qs",
    "Decompositions/CNOTControlled.qs",
    "Decompositions/CNOTAdjointControlled.qs",
    "Decompositions/CNOTControlledAdjoint.qs",
    "Decompositions/CX.qs",
    "Decompositions/CXAdjoint.qs",
    "Decompositions/CXControlled.qs",
    "Decompositions/CXAdjointControlled.qs",
    "Decompositions/CXControlledAdjoint.qs",
    "Decompositions/CY.qs",
    "Decompositions/CYAdjoint.qs",
    "Decompositions/CYControlled.qs",
    "Decompositions/CYAdjointControlled.qs",
    "Decompositions/CYControlledAdjoint.qs",
    "Decompositions/CZ.qs",
    "Decompositions/CZAdjoint.qs",
    "Decompositions/CZControlled.qs",
    "Decompositions/CZAdjointControlled.qs",
    "Decompositions/CZControlledAdjoint.qs",
    # TODO(tfr):   "Decompositions/ExpFrac.qs",
    # TODO(tfr): "Decompositions/ExpFracAdjoint.qs",
    # TODO(tfr): "Decompositions/ExpFracControlled.qs",
    # TODO(tfr): "Decompositions/ExpFracAdjointControlled.qs",
    # TODO(tfr): "Decompositions/ExpFracControlledAdjoint.qs",
    "Decompositions/H.qs",
    "Decompositions/HAdjoint.qs",
    "Decompositions/HControlled.qs",
    "Decompositions/HAdjointControlled.qs",
    "Decompositions/HControlledAdjoint.qs",
    "Decompositions/I.qs",
    "Decompositions/IAdjoint.qs",
    "Decompositions/IControlled.qs",
    "Decompositions/IAdjointControlled.qs",
    "Decompositions/IControlledAdjoint.qs",
    "Decompositions/M.qs",
    "Decompositions/MResetX.qs",
    "Decompositions/MResetY.qs",
    "Decompositions/MResetZ.qs",
    "Decompositions/R.qs",
    "Decompositions/RAdjoint.qs",
    "Decompositions/RControlled.qs",
    "Decompositions/RAdjointControlled.qs",
    "Decompositions/RControlledAdjoint.qs",
    "Decompositions/R1.qs",
    "Decompositions/R1Adjoint.qs",
    "Decompositions/R1Controlled.qs",
    "Decompositions/R1AdjointControlled.qs",
    "Decompositions/R1ControlledAdjoint.qs",
    "Decompositions/R1Frac.qs",
    "Decompositions/R1FracAdjoint.qs",
    "Decompositions/R1FracControlled.qs",
    "Decompositions/R1FracAdjointControlled.qs",
    "Decompositions/R1FracControlledAdjoint.qs",
    "Decompositions/RFrac.qs",
    "Decompositions/RFracAdjoint.qs",
    "Decompositions/RFracControlled.qs",
    "Decompositions/RFracAdjointControlled.qs",
    "Decompositions/RFracControlledAdjoint.qs",
    "Decompositions/Reset.qs",
    "Decompositions/ResetAdjoint.qs",
    "Decompositions/ResetControlled.qs",
    "Decompositions/ResetAdjointControlled.qs",
    "Decompositions/ResetControlledAdjoint.qs",
    "Decompositions/Rx.qs",
    "Decompositions/RxAdjoint.qs",
    "Decompositions/RxControlled.qs",
    "Decompositions/RxAdjointControlled.qs",
    "Decompositions/RxControlledAdjoint.qs",
    "Decompositions/Ry.qs",
    "Decompositions/RyAdjoint.qs",
    "Decompositions/RyControlled.qs",
    "Decompositions/RyAdjointControlled.qs",
    "Decompositions/RyControlledAdjoint.qs",
    "Decompositions/Rz.qs",
    "Decompositions/RzAdjoint.qs",
    "Decompositions/RzControlled.qs",
    "Decompositions/RzAdjointControlled.qs",
    "Decompositions/RzControlledAdjoint.qs",
    "Decompositions/S.qs",
    "Decompositions/SAdjoint.qs",
    "Decompositions/SControlled.qs",
    "Decompositions/SAdjointControlled.qs",
    "Decompositions/SControlledAdjoint.qs",
    "Decompositions/SWAP.qs",
    "Decompositions/SWAPAdjoint.qs",
    "Decompositions/SWAPControlled.qs",
    "Decompositions/SWAPAdjointControlled.qs",
    "Decompositions/SWAPControlledAdjoint.qs",
    "Decompositions/SetToBasisState.qs",
    "Decompositions/T.qs",
    "Decompositions/TAdjoint.qs",
    "Decompositions/TControlled.qs",
    "Decompositions/TAdjointControlled.qs",
    "Decompositions/TControlledAdjoint.qs",
    "Decompositions/X.qs",
    "Decompositions/XAdjoint.qs",
    "Decompositions/XControlled.qs",
    "Decompositions/XAdjointControlled.qs",
    "Decompositions/XControlledAdjoint.qs",
    "Decompositions/Y.qs",
    "Decompositions/YAdjoint.qs",
    "Decompositions/YControlled.qs",
    "Decompositions/YAdjointControlled.qs",
    "Decompositions/YControlledAdjoint.qs",
    "Decompositions/Z.qs",
    "Decompositions/ZAdjoint.qs",
    "Decompositions/ZControlled.qs",
    "Decompositions/ZAdjointControlled.qs",
    "Decompositions/ZControlledAdjoint.qs",
]

available3 = ["Intrinsic/ApplyControlledX.qs",
              "Intrinsic/ApplyControlledZ.qs",
              "Intrinsic/ApplyUncontrolledH.qs",
              "Intrinsic/ApplyUncontrolledRx.qs", "Intrinsic/ApplyUncontrolledRy.qs", "Intrinsic/ApplyUncontrolledRz.qs", "Intrinsic/ApplyUncontrolledS.qs", "Intrinsic/ApplyUncontrolledSAdj.qs", "Intrinsic/ApplyUncontrolledSWAP.qs", "Intrinsic/ApplyUncontrolledT.qs", "Intrinsic/ApplyUncontrolledTAdj.qs", "Intrinsic/ApplyUncontrolledX.qs", "Intrinsic/ApplyUncontrolledY.qs", "Intrinsic/ApplyUncontrolledZ.qs", "Intrinsic/MZ.qs", "Intrinsic/Reset.qs", "Decompositions/AssertOperationsEqualInPlace.qs", "Decompositions/AssertOperationsEqualReferenced.qs", "Decompositions/CCNOTFromCCZ.qs", "Decompositions/CNOTFromSinglyControlled.qs", "Decompositions/CX.qs", "Decompositions/CYFromCNOT.qs", "Decompositions/CZFromSinglyControlled.qs", "Decompositions/ExpFracFromExpUtil.qs", "Decompositions/ExpFromExpUtil.qs", "Decompositions/ExpUtil.qs",
              "Decompositions/HFromSinglyControlled.qs", "Decompositions/I.qs", "Decompositions/Measure.qs", "Decompositions/MResetXExplicit.qs", "Decompositions/MResetYExplicit.qs", "Decompositions/MResetZExplicit.qs", "Decompositions/MWithPostPrep.qs", "Decompositions/PreparePostMNoop.qs", "Decompositions/RFromSinglyControlledR1.qs", "Decompositions/R1FromSinglyControlled.qs", "Decompositions/R1Frac.qs", "Decompositions/ResetAll.qs", "Decompositions/RFrac.qs", "Decompositions/RxFromSinglyControlled.qs", "Decompositions/RyFromSinglyControlled.qs", "Decompositions/RzFromSinglyControlled.qs", "Decompositions/SFromSinglyControlled.qs", "Decompositions/SWAPFromSinglyControlled.qs", "Decompositions/TFromSinglyControlled.qs", "Decompositions/XFromSinglyControlled.qs", "Decompositions/YFromSinglyControlled.qs", "Decompositions/ZFromSinglyControlled.qs", "Decompositions/SetToBasisState.qs", "Decompositions/Utils.qs"]

available4 = ["Intrinsic/ApplyControlledX.qs", "Intrinsic/ApplyControlledZ.qs", "Intrinsic/ApplyUncontrolledH.qs", "Intrinsic/ApplyUncontrolledRx.qs", "Intrinsic/ApplyUncontrolledRy.qs", "Intrinsic/ApplyUncontrolledRz.qs", "Intrinsic/ApplyUncontrolledS.qs", "Intrinsic/ApplyUncontrolledSAdj.qs", "Intrinsic/ApplyUncontrolledSWAP.qs", "Intrinsic/ApplyUncontrolledT.qs", "Intrinsic/ApplyUncontrolledTAdj.qs", "Intrinsic/ApplyUncontrolledX.qs", "Intrinsic/ApplyUncontrolledY.qs", "Intrinsic/ApplyUncontrolledZ.qs", "Intrinsic/MZ.qs", "Intrinsic/Reset.qs", "Decompositions/AssertOperationsEqualInPlace.qs", "Decompositions/AssertOperationsEqualReferenced.qs", "Decompositions/CCNOTFromCCZ.qs", "Decompositions/CNOTFromSinglyControlled.qs", "Decompositions/CX.qs", "Decompositions/CYFromCNOT.qs", "Decompositions/CZFromSinglyControlled.qs", "Decompositions/ExpFracFromExpUtil.qs", "Decompositions/ExpFromExpUtil.qs",
              "Decompositions/ExpUtil.qs", "Decompositions/HFromSinglyControlled.qs", "Decompositions/I.qs", "Decompositions/M.qs", "Decompositions/MeasureWithNoReuse.qs", "Decompositions/MResetXExplicit.qs", "Decompositions/MResetYExplicit.qs", "Decompositions/MResetZExplicit.qs", "Decompositions/PreparePostMNoop.qs", "Decompositions/RFromSinglyControlledR1.qs", "Decompositions/R1FromSinglyControlled.qs", "Decompositions/R1Frac.qs", "Decompositions/ResetAll.qs", "Decompositions/RFrac.qs", "Decompositions/RxFromSinglyControlled.qs", "Decompositions/RyFromSinglyControlled.qs", "Decompositions/RzFromSinglyControlled.qs", "Decompositions/SFromSinglyControlled.qs", "Decompositions/SWAPFromSinglyControlled.qs", "Decompositions/TFromSinglyControlled.qs", "Decompositions/XFromSinglyControlled.qs", "Decompositions/YFromSinglyControlled.qs", "Decompositions/ZFromSinglyControlled.qs", "Decompositions/SetToBasisState.qs", "Decompositions/Utils.qs"]
