site_name: QAT Documentation
site_url: https://qir-alliance.github.io/qat/
base_url: /qat/
docs_dir: src
site_description: Everything you need to know about QAT API.
site_author: troels
extra_css:
  - css/quantum-colors.css
markdown_extensions:
  - admonition

plugins:
  - search

theme:
  name: null
  custom_dir: "tailwind_theme/"
  theme_dir: "tailwind_theme/"
  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: false

  highlightjs: true
  hljs_languages:
    - bash
    - cpp
    - python
    - llvm

  hljs_style: "monokai-sublime"

  navigation_depth: 2
  nav_style: primary

  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s

nav:
  - Quick start:
      - Quick start: "QuickStart/index.md"
      - Building with Bazel: "QuickStart/building-with-bazel.md"
      - Building with CMake: "QuickStart/building-with-cmake.md"
      - Running QAT: "QuickStart/running-qat.md"

  - Using QAT:
      - Targeting a QIR: "UsingQAT/TargetingQIR.md"
      - Debugging a QIR: "UsingQAT/DebuggingIR.md"
      - Assumptions and restrictions: "UsingQAT/GoalsAndAssumptions.md"

  - Developer guide:
      - Architecture Overview: "DeveloperGuide/ArchitectureOverview.md"
      - Writing an adaptor: "DeveloperGuide/WritingAdaptor.md"
      - Rule based extensions: "DeveloperGuide/WritingRuleTests.md"
      - Grouping QIS: "DeveloperGuide/LogicSeparation.md"

  - Api:
      - Classes: "Api/Classes/"
      - Namespaces: "Api/Namespaces/"
      - Modules: "Api/Modules/"

  - Contributing:
      - Code quality: "DeveloperGuide/CodeQuality.md"
      - Developer FAQ: "DeveloperGuide/DeveloperFAQ.md"
