name: "Linux CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Linux CI"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Installing dependencies"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y 
          sudo apt-get remove -y llvm-12
          sudo apt-get install -y curl pkg-config findutils  wget
          sudo apt install -y clang-11 cmake clang-format-11 clang-tidy-11 
          sudo apt-get install -y llvm-11 lldb-11 llvm-11-dev libllvm11 llvm-11-runtime opt 
          sudo apt-get install -y nodejs npm
          sudo apt install -y python3 python3-pip 
          sudo apt-get remove -y llvm-10
          sudo ln -s /usr/lib/llvm-11/bin/opt /usr/bin/opt
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 0       
          dotnet tool install --global Microsoft.Quantum.IQSharp --version 0.20.2110171573          
          git submodule update --init --recursive
          pip install -r requirements.txt  
          npm install -g prettier@2.2.1
          chmod +x manage
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11

      - name: "Checking format"
        run: |
          ./manage stylecheck
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11

      - name: "Running unit tests"
        run: |
          ./manage test
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11

      - name: "Running QIR tests"
        run: |
          pip install pytest
          pip install -r requirements.txt
          cd qir/qir-tests/
          pytest
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11

      - name: "Running examples"
        run: |
          make test-examples
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11

      - name: "Running Qiskit tests"
        run: |
          pip install https://github.com/qir-alliance/pyqir/releases/download/v0.2.0a1/pyqir_generator-0.2.0a1-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          pip install https://github.com/qir-alliance/pyqir/releases/download/v0.2.0a1/pyqir_jit-0.2.0a1-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          pip install https://github.com/qir-alliance/pyqir/releases/download/v0.2.0a1/pyqir_parser-0.2.0a1-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

          git clone git@github.com:microsoft/qdk-python.git
          git checkout feature/qir-submission          
          pushd qdk-python/qiskit-qir
          pip install -e .
          popd
          export PYTHONPATH=$PWD/qdk-python/qiskit-qir/tests:$PYTHONPATH

          pushd qir/qiskit-tests/
          pip install pytest
          pytest
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11

      - name: "Performing static analysis"
        run: |
          ./manage lint
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11
