name: "Linux CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-22.04
    name: "Linux CI"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: "Installing dependencies"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y 
          sudo apt-get remove -y llvm-12 llvm-11 clang-format-11 clang-tidy-11 clang-format-14 clang-tidy-14 
          sudo apt-get install -y curl pkg-config findutils  wget
          sudo apt install -y clang-13 cmake clang-format-13 clang-tidy-13 
          sudo apt-get install -y llvm-13 lldb-13 llvm-13-dev libllvm11 llvm-13-runtime opt 
          sudo apt-get install -y nodejs npm
          sudo apt install -y python3 python3-pip 
          sudo ln -s /usr/lib/llvm-13/bin/opt /usr/bin/opt
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 0       
          dotnet tool install --global Microsoft.Quantum.IQSharp --version 0.20.2110171573          
          git submodule update --init --recursive
          pip install -r requirements.txt  
          npm install -g prettier@2.2.1
          chmod +x manage
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13

      - name: "Checking format"
        run: |
          ./manage stylecheck
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13

      - name: "Running unit tests"
        run: |
          ./manage test
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13

      - name: "Running Q# tests"
        run: |
          git clone https://github.com/microsoft/Quantum.git
          export QAT_BINARY=${PWD}/Debug/qir/qat/Apps/qat     
          export QSHARP_SAMPLES=${PWD}/Quantum/samples    

          pushd qir/qsharp-tests/
          pip3 install --user pytest
          pytest

      - name: "Running QIR tests"
        run: |
          mkdir -p Debug
          pushd Debug
          cmake ..
          make -j qat
          popd

          export QAT_BINARY=${PWD}/Debug/qir/qat/Apps/qat        
          pip install pytest
          pip install -r requirements.txt
          cd qir/qir-tests/
          pytest
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13

      - name: "Running examples"
        run: |
          make test-examples
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13

      - name: "Performing static analysis"
        run: |
          ./manage lint
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13
