name: "macOS CI Bazel"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-12
    name: "Mac CI Bazel"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "Running debug unit tests"
        run: |
          bazelisk test --config clang --config debug --feature asan --feature ubsan //qir/...
        env:
          CC: clang
          CXX: clang++

      - name: "Running unit tests"
        run: |
          bazelisk test --config clang //qir/...
        env:
          CC: clang
          CXX: clang++
