name: "macOS CI Bazel"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-12
    name: "Mac CI Bazel"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Bazel cache
        id: cache-bazel
        uses: actions/cache@v3.0.4
        with:
          path: ~/.cache/bazel/
          key: ${{ runner.os }}-bazel

      - name: "Running debug unit tests with address sanitation"
        run: |
          bazelisk test --keep_going --disk_cache=~/.cache/bazel/ --config clang --config debug --features asan //qir/...
        env:
          CC: clang
          CXX: clang++

      - name: "Running unit tests"
        run: |
          bazelisk test --keep_going --disk_cache=~/.cache/bazel/ --config clang //qir/...
        env:
          CC: clang
          CXX: clang++

      - name: "Testing build"
        run: |
          bazelisk build --keep_going --disk_cache=~/.cache/bazel/ --config clang //qir/...
        env:
          CC: clang
          CXX: clang++
