name: "windows CI Bazel"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-2022
    name: "Bazel Build"
    steps:
      - name: Get Timestamp
        id: timestamp
        run: Write-Host "::set-output name=timestamp::$([DateTime]::UtcNow.ToString('o'))"
        shell: pwsh

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Bazel cache
        id: cache-bazel
        uses: actions/cache@v3.0.4
        with:
          path: ~/.cache/bazel/
          key: ${{ runner.os }}-bazel-${{ steps.timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: "Building release"
        run: |
          bazelisk build --config msvc --disk_cache=~/.cache/bazel/ //qir/...

  test:
    runs-on: windows-2022
    name: "Bazel Test"
    needs: [build]
    steps:
      - name: Get Timestamp
        id: timestamp
        run: Write-Host "::set-output name=timestamp::$([DateTime]::UtcNow.ToString('o'))"
        shell: pwsh

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Bazel cache
        id: cache-bazel
        uses: actions/cache@v3.0.4
        with:
          path: ~/.cache/bazel/
          key: ${{ runner.os }}-bazel-${{ steps.timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: "Running unit tests"
        run: |
          bazelisk test --test_output=all --keep_going --config msvc --disk_cache=~/.cache/bazel/ //qir/...
        env:
          CC: clang.exe
          CXX: clang++
