name: "windows CI Bazel"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-2022
    name: "Bazel Build"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Bazel cache
        id: cache-bazel
        uses: actions/cache@v3.0.4
        with:
          path: bazel-cache/
          key: ${{ runner.os }}-bazel

      - name: "Building release"
        run: |
          bazelisk build --config msvc --disk_cache=bazel-cache/ //qir/...

  test:
    runs-on: windows-2022
    name: "Bazel Test"
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Bazel cache
        id: cache-bazel
        uses: actions/cache@v3.0.4
        with:
<<<<<<< HEAD
          path: ~/.cache/bazel/
          key: ${{ matrix.config.os }}-${{ matrix.config.target }}-bazel
=======
          path: bazel-cache/
          key: ${{ runner.os }}-bazel
>>>>>>> c110434393b62ff7296b04a8684fcd206d224901

      - name: "Running unit tests"
        run: |
          bazelisk test --test_output=all --keep_going --config msvc --disk_cache=bazel-cache/ //qir/...
        env:
          CC: clang.exe
          CXX: clang++
