name: "Q# target testing"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-22.04
    name: "Target testing"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: "Installing dependencies"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y
          sudo apt-get install -y --no-install-recommends curl cmake pkg-config findutils wget
          sudo apt-get remove -y clang-13 llvm-13 clang-format-13 clang-tidy-13 clang-12 llvm-12 clang-format-12 clang-tidy-12
          sudo apt install -y --no-install-recommends clang-14 llvm-14 clang-format-14 clang-tidy-14
          sudo apt-get install -y nodejs npm
          sudo apt install -y python3 python3-pip 
          sudo ln -s /usr/lib/llvm-14/bin/opt /usr/bin/opt
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 0       
          dotnet tool install --global Microsoft.Quantum.IQSharp --version 0.25.218240          
          git submodule update --init --recursive
          pip install -r requirements.txt  
          npm install -g prettier@2.2.1
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-14
          CXX: clang++-14

      - name: "Running target tests"
        run: |
          mkdir -p Debug
          pushd Debug
          cmake ..
          make qat
          popd

          export QAT_BINARY=${PWD}/Debug/qir/qat/Apps/qat        
          pip install pytest
          pip install -r requirements.txt
          cd qir/qsharp-target-tests/
          pytest
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-14
          CXX: clang++-14
