name: "Q# target testing"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-22.04
    name: "Target testing"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: "Installing dependencies"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y 
          sudo apt-get remove -y llvm-12 llvm-14 llvm-11 clang-11 clang-format-11 clang-tidy-11 clang-format-14 clang-tidy-14 
          sudo apt-get install -y curl pkg-config findutils  wget
          sudo apt install -y clang-13 cmake clang-format-13 clang-tidy-13 
          sudo apt-get install -y llvm-13 lldb-13 llvm-13-dev libllvm11 llvm-13-runtime opt 
          sudo apt-get install -y nodejs npm
          sudo apt install -y python3 python3-pip 
          sudo ln -s /usr/lib/llvm-13/bin/opt /usr/bin/opt
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 0       
          dotnet tool install --global Microsoft.Quantum.IQSharp --version 0.24.201332          
          git submodule update --init --recursive
          pip install -r requirements.txt  
          npm install -g prettier@2.2.1
          chmod +x manage
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13

      - name: "Running target tests"
        run: |
          mkdir -p Debug
          pushd Debug
          cmake ..
          make -j qat
          popd

          export QAT_BINARY=${PWD}/Debug/qir/qat/Apps/qat        
          pip install pytest
          pip install -r requirements.txt
          cd qir/qsharp-target-tests/
          pytest
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13
