name: "Trusted Linux CI"

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Trusted Linux CI"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: "Copying QAT source"
        run: |
          cp -R qir/qat /tmp/


      - name: Checkout code main
        uses: actions/checkout@v2
        with:          
          ref: "main"
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: "Replacing QAT source"
        run: |
          rm -rf qir/qat
          mv /tmp/qat qir/

      - name: "Building QAT"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y 
          sudo apt-get remove -y llvm-12
          sudo apt-get install -y curl pkg-config findutils  wget
          sudo apt install -y clang-11 cmake clang-format-11 clang-tidy-11 
          sudo apt-get install -y llvm-11 lldb-11 llvm-11-dev libllvm11 llvm-11-runtime opt 
          sudo apt-get install -y nodejs npm
          sudo apt install -y python3 python3-pip 
          sudo apt-get remove -y llvm-10
          sudo ln -s /usr/lib/llvm-11/bin/opt /usr/bin/opt
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 0       
          dotnet tool install --global Microsoft.Quantum.IQSharp --version 0.20.2110171573          
          git submodule update --init --recursive
          pip install -r requirements.txt  
          npm install -g prettier@2.2.1          
          chmod +x manage
          mkdir Debug
          cd Debug
          cmake .. 
          make qat          
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11


      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.QISKIT_KEY }}

