name: "Trusted macOS CI"

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-11
    name: "Trusted Mac CI"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: "Copying QAT source"
        run: |
          cp -R qir/qat /tmp/
          cp -R qir/qiski-tests /tmp/

      - name: Checkout code main
        uses: actions/checkout@v2
        with:
          ref: "main"
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: "Replacing QAT source"
        run: |
          rm -rf qir/qat
          rm -rf qir/qiskit-tests
          mv /tmp/qat qir/
          mv /tmp/qiskit-tests qir/

      - name: "Building QAT"
        run: |
          rm '/usr/local/bin/2to3'
          brew install llvm@11
          brew install cmake
          brew install python@3.9
          brew unlink python@3.9
          brew install node@16
          brew link python@3.9
          echo "/Users/runner/Library/Python/3.9/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/llvm@11/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/node@16/bin" >> $GITHUB_PATH
          echo "/Users/runner/Library/Python/3.9/lib/python/bin" >> $GITHUB_PATH
          echo "/usr/local/bin/$HOME/bin" >> $GITHUB_PATH
          git submodule update --init --recursive
          pip3 install --user -r requirements.txt
          python3 -c "import autopep8;print(autopep8.__file__)"
          dotnet tool install --global Microsoft.Quantum.IQSharp --version 0.20.2110171573
          npm install -g prettier@2.2.1
          chmod +x manage
          exec -l $SHELL

      - name: "Build project"
        run: |
          mkdir -p Debug
          cd Debug
          cmake .. -DMICROSOFT_ENABLE_DYNAMIC_LOADING=0
          make qat
        env:
          LDFLAGS: "-L/usr/local/opt/llvm@11/lib -Wl,-rpath,/usr/local/opt/llvm@11/lib"
          CPPFLAGS: "-I/usr/local/opt/llvm@11/include"
          CC: clang
          CXX: clang++

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.QISKIT_KEY }}

      - name: "Running Qiskit tests"
        run: |
          git clone git@github.com:msr-quarc/qiskit-qir.git
          pushd qiskit-qir
          pip3 install --user -e .
          popd
          export PYTHONPATH=$PWD/qiskit-qir/tests:$PYTHONPATH
          export QAT_BINARY=${PWD}/Debug/qir/qat/Apps/qat     

          pushd qir/qiskit-tests/
          pip3 install --user pytest
          pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CC: clang-11
          CXX: clang++-11
