name: "Linux Release"

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: "Upload Release Asset"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Installing dependencies"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y 
          sudo apt-get remove -y llvm-12 llvm-11 clang-format-11 clang-tidy-11 
          sudo apt-get install -y curl pkg-config findutils  wget
          sudo apt install -y clang-13 cmake clang-format-13 clang-tidy-13 
          sudo apt-get install -y llvm-13 lldb-13 llvm-13-dev libllvm11 llvm-13-runtime opt 
          sudo apt-get install -y nodejs npm
          sudo apt install -y python3 python3-pip 
          sudo ln -s /usr/lib/llvm-13/bin/opt /usr/bin/opt
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 0       
          dotnet tool install --global Microsoft.Quantum.IQSharp --version 0.20.2110171573          
          git submodule update --init --recursive
          pip install -r requirements.txt  
          npm install -g prettier@2.2.1
          chmod +x manage
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13

      - name: "Running unit tests"
        run: |
          ./manage test
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13

      - name: "Build project"
        run: |
          mkdir -p Release
          cd Release
          cmake ..
          make qat
          cd ..
          mv Release/qir/qat/Apps/qat ./
          chmod +x qat
          tar cf qat-ubuntu-22.zip qat
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-13
          CXX: clang++-13

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./qat-ubuntu-22.zip
          asset_name: qat-ubuntu-22.zip
          asset_content_type: application/zip
