name: "Mac Release"

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: "Upload Release Asset"
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Installing dependencies"
        run: |
          rm '/usr/local/bin/2to3'
          brew install llvm@13
          brew install cmake
          brew install python@3.9
          brew unlink python@3.9
          brew install node@16
          brew link python@3.9
          echo "/Users/runner/Library/Python/3.9/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/llvm@13/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/node@16/bin" >> $GITHUB_PATH
          echo "/Users/runner/Library/Python/3.9/lib/python/bin" >> $GITHUB_PATH
          echo "/usr/local/bin/$HOME/bin" >> $GITHUB_PATH
          git submodule update --init --recursive
          pip3 install --user -r requirements.txt
          python3 -c "import autopep8;print(autopep8.__file__)"
          dotnet tool install --global Microsoft.Quantum.IQSharp --version 0.20.2110171573
          npm install -g prettier@2.2.1
          exec -l $SHELL

      - name: "Build project"
        run: |
          mkdir -p Release
          cd Release
          cmake .. -DMICROSOFT_ENABLE_DYNAMIC_LOADING=0
          make qat
          cd ..
          mv Release/qir/qat/Apps/qat ./
          chmod +x qat
          tar cf qat-mac.zip qat
        env:
          LDFLAGS: "-L/usr/local/opt/llvm@13/lib -Wl,-rpath,/usr/local/opt/llvm@13/lib"
          CPPFLAGS: "-I/usr/local/opt/llvm@13/include"
          CC: clang
          CXX: clang++

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./qat-mac.zip
          asset_name: qat-mac.zip
          asset_content_type: application/zip
